version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./tools:/app/tools
      - ./main.py:/app/main.py
    environment:
      - FLASK_ENV=development
    container_name: library-app-dev